services:
  tester:
    container_name: tester
    image: golang:1.24-bullseye
    working_dir: /tmp/lockbox/integration-tests/tester
    command: /tmp/assets/entrypoint.sh
    environment:
      - TEST_NAME=${TEST_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../:/tmp/lockbox:rw
      - ../logs:/tmp/logs
      - ../assets:/tmp/assets
      - lockbox-testing-cache:/go
      - lockbox-testing-assets:/assets

volumes:
  lockbox-testing-cache:
    external: true
    name: lockbox-testing-cache
  lockbox-testing-assets:
    external: true
    name: lockbox-testing-assets
